### ISSUE TITLE
Why do we normalize the surfaceToView vector in both vertex and frag shaders?

### ISSUE THREAD

**Issue by trusktr** [greggman/webgl-fundamentals#80]
In the tutorial, why do we do

```glsl
  v_surfaceToView = normalize(u_viewWorldPosition - surfaceWorldPosition);
```

in the vertex shader, *and*

```glsl
  vec3 surfaceToViewDirection = normalize(v_surfaceToView);
```

in the fragment shader? Can you explain why normalizing only in the frag shader does not have the same result?

Maybe an indirect question would help in general: how does the interpolation of vertices' varying vectors across the fragments work? Maybe that has something to do with it?

**Comment by trusktr** [comment]
The reason I ask, is because mathematically, the following two codes in the non-GPU paradigm seem equivalent (written in JS for example):

```js
  var v_surfaceToView = vec3.normalize(vec3.subtract(u_viewWorldPosition, surfaceWorldPosition));
  var surfaceToViewDirection = vec3.normalize(v_surfaceToView);
```


```js
  var v_surfaceToView = vec3.subtract(u_viewWorldPosition, surfaceWorldPosition);
  var surfaceToViewDirection2 = vec3.normalize(v_surfaceToView);
```

```js
console.log(vec3.areEqual(surfaceToViewDirection, surfaceToViewDirection2)) // true
```

Because, in this non-distributed non-GPU case, doesn't normalizing a second yield the same result? i.e. normalizing a unit vector results in the same unit vector right?

But in the GPU distributed computing paradigm, there's a behavior that is not aligned with the above expectation: when I do not normalize in the vertex shader I get different results than if I do.

What gives? Why does normalizing twice give different results?

**Comment by greggman** [comment]
![varying](https://cloud.githubusercontent.com/assets/234804/26621308/5fc9587e-4621-11e7-9de8-b2c2bc3a4207.png)

Here's 2 points with normals (normals are the green lines on each edge). The 2 points are the endpoints of the black line.

The top example the normals are normalized before interpolation

The bottom example the right normal is pointing the same direction as the top but has a length of 5. 

Red lines are the interpolated values that are then normalized and drawn at each corresponding point

https://jsfiddle.net/greggman/4v0vL5gf/

**Comment by trusktr** [comment]
@greggman Wow Greg, that was extremely helpful. You are THE MAN (no pun intended). Thanks a ton, that fiddle is awesome!! Now I understand exactly what is happening.

It makes sense if we look at the green line sticking way out, although it is in the same direction, the interpolation for the X values goes along a much wider range, so it really isn't the same as interpolating the smaller range of X values if we normalize in the vertex shaders first.

One last question: in the generated image, why are the red lines not all the same length? Or is it just a visual illusion?

**Comment by trusktr** [comment]
It really is an optical illusion! I made the scale bigger, and stuck a ruler up to the screen and they are all the same length!

**Comment by trusktr** [comment]
Oh! One last question: How *does* WebGL interpolate? Does it

1. interpolate from item in array to corresponding item in array (for example, for two mat4s called m1 and m2, it would interpolate between m1[0] and m2[0], between m1[1] and m2[1], between m1[2] and m2[2], etc, between all items of the same index)?
2. use a non-linear interpolation since there are three vertices?

I don't care too much about the second question, but mainly I just want to know if items of matching index are interpolated just the same way as interpolation between two `varying float` variables.

**Comment by greggman** [comment]
I'm not sure I understand your question. Varyings are interpreted by matching names so there is no interpolation between m1 and m2.  In the vertex shader you declare a varying and write to it

     varying vec2 foo;

     void main() {
         foo = ???
     }

In the fragment shader you look at foo by declaring a matching varying

     varying vec2 foo;

The values are automatically interpolated between the 2 or 3 points of the primitive (LINE or TRIANGLE). 

If the names don't match or their types are different or their precisions don't match in a compatible way you'll get an error when trying to link the program.

The interpolation is linear AFAIK it's just between 3 points instead of 2 if it's a triangle. The formula is in the [spec section 3.5.1](https://www.khronos.org/registry/OpenGL/specs/es/2.0/es_full_spec_2.0.pdf)

**Comment by trusktr** [comment]
By `m1 and m2` I mean, for example, the `varying m` of each of the three vertices. So for each vertex (of three, TRIANGLE), the values interpolated are the three values that are in the same index of the varying value of each vertex? Does that make sense?

SO what I meant is that `m1` is the varying value of the first matrix, `m2` is the varying value of the same name in the second vertex, and `m3` would be the varying value of the same name in the third vertex.

So based on that definition of `m1, m2, m3`, I just wanted to confirm that interpolation happens between three values, where each value is at the same index in its corresponding multi-component value. For example, interpolation happens between `m1[0]`, `m2[0]`, `m3[0]`, between `m1[1]`, `m2[1]`, `m3[1]`.

Seems like that is what is implied, but wanted to confirm.

**Comment by trusktr** [comment]
Why is it that we normalize the surface2camera vector twice (once in vert and once in frag), but we only normalize the surface2light vector [only once](https://github.com/greggman/webgl-fundamentals/blob/master/webgl/webgl-3d-lighting-point-specular.html#L50-L54)?

**Comment by greggman** [comment]
Neither should be normalized in the vertex shader. I've updated the code. That was something I added to try to work around precisions issues in old mobile phones. For a moment I thought it worked but it didn't actually work and it was wrong.

See https://jsfiddle.net/greggman/mnanrf1s/

The pink and lightblue lines are not normalized interpolations. The red and blue lines are. You can see the normalized interpolations don't point in the correct direction.

They're off subtly so it's not clear when rendering that they were wrong. 

This brings up a differen issue though which I'll have to add something to about. That issue is precison. On desktops all floating point math in the GPU is at least 32bit. On Mobile it depends. The WebGL spec (the OpenGL ES 2.0 spec) says that 32bit precision (`highp`) is an optional feature and plenty of old phones (iPhone 3GS era) don't support highp. That's way I use `mediump` everywhere.  That way all the samples run (or should run) even on old phones.

But, it turns out `mediump` does not have enough precision to interpolate world vectors and so if you go view the specular sample on a phone you'll see it's blown out.

There is no *easy* solution. The solutions are

1. Figure out some way to make the math not need as high precision

   not sure how to do that honestly (well I haven't really thought about it). 

2. Fall back to shaders that don't use need high precision

   In this case you'd ask WebGL if it supports high precision and if not use a different shader, maybe one that doesn't support specular highlights at all

3. Require highp

  You could just make your shader use `highp` and either just let it fail on old phones or check if the phone doesn't support highp and tell the use "sorry, get a new phone"

4. Use `highp` if it exists and fall back to `mediump` if it doesn't and basically don't worry that it doesn't look perfect on an old phone. You can do this by adding something like this to the shader

        #if GL_FRAGMENT_PRECISION_HIGH
          precision highp float;
        #else
          precision mediump float;
        #endif
   
   This will make it at least run on an old phone even if it doesn't look correct. Unfortunately it's also not the perfect solution because `highp` is slower on phones than `mediump` so ideally you'd just want to mark just those things that need highp

        precision mediump float;   // default to mediump

        #if GL_FRAGMENT_PRECISION_HIGH
          varying highp v_surfaceToView;
          varying highp v_surfaceToLight;
        #else
          varying mediump v_surfaceToView;
          varying medump v_surfaceToLight;
        #endif

        varying vec3 v_normal;   // uses the default

    or you could do something like this

        #if GL_FRAGMENT_PRECISION_HIGH
          #define OPTIONALHIGHP highp
        #else
          #define OPTIONALHIGHP mediump
        #endif
        
        varying OPTIONALHIGHP v_surfaceToView;
        varying OPTIONALHIGHP v_surfaceToLight;
        varying vec3 v_normal;

I'd probably 4 but I'm not sure I want to clutter the examples with all that stuff. I'll have to think about it.

**Comment by trusktr** [comment]
> The pink and lightblue lines are not normalized interpolations. The red and blue lines are. You can see the normalized interpolations don't point in the correct direction.

So these are the interpolations with and without normalization in the vertex shader. Interesting! Thanks for this detail and info on the precision.

**Comment by trusktr** [comment]
I understand conceptually what you've described, which makes sense, but when I try and remove the `normalize()` call from the vertex shader, the result looks nothing like shininess at all. It doesn't even seem to behave like proper light like it at least does if I leave the `normalize()` call in. 

Here's my program *with* `normalize()` in the vertex shader: https://jsfiddle.net/bm0mubm8/1
And here's *without* normalize in the vertex shader: https://jsfiddle.net/bm0mubm8/2

In each one, the light is moving in a circle around the whole thing, at a radius of 600, making a circle who's plane is y=-200.

In either case, I'm not sure that the light looks correct, but at least in the first one the light looks more correct.

In the first one, you'll see on the second cube from the top, on the left side, the light reflection for a brief moment as the light passes from behind to left. But when it passes in front the reflection isn't sharp like it is on the left side, but more of a larger gradient.

Then in the second example, the light doesn't seem to look like a light at all, the shininess creeps in from the left, then back to the left.

Did I do something wrong?

**Comment by greggman** [comment]
This line

          vec3 halfVector = normalize(surfaceToLightDirection + v_surfaceToCameraVector);

needs to be this

          vec3 halfVector = normalize(surfaceToLightDirection + surfaceToCameraDirection);

**Comment by trusktr** [comment]
Oops, my mistake. Not sure how I missed it. Thanks!

**Comment by trompx** [comment]
@greggman Awesome!!! thanks for the great explanations.

I had a really weird issue I could not debug, I started changing a lot of stuff until I found out that **changing the precision** solved the problem (on **ios**). I kept looking to understand what is going on and ended up here.

Use case
---------

I draw a rectangle with a texture and I apply a distorsion based on another texture (displacement map).
I create the distorsion texture with:
```
this.gl.texParameteri(this.gl.TEXTURE_2D, this.gl.TEXTURE_WRAP_S, this.gl.REPEAT),
this.gl.texParameteri(this.gl.TEXTURE_2D, this.gl.TEXTURE_WRAP_T, this.gl.REPEAT),
```

In js, I set u_time = time of rAF.

The fragment shader has:
```
float time = u_time * speed;
vec2 displacement = texture2D(u_displacementTexture, 0.4 * v_texCoord + time).rg * 2.0 - 1.0;
vec2 uv = v_texCoord + displacement * u_displace_factor;
gl_FragColor = texture2D(u_projectImage, uv)
```

On desktop, the code run butterly smooth, on IOS (ipad and iphone), the animation is at start butterly smooth too, but 20 or 30 seconds later, it starts getting slower and slower. I thought at first there had to be some rendering issue making the fps drops but not at all, the fps was still peaking at 60fps... weird

I had not much clues about what was slowing the animation down.
Hypothesis: as the displacement texture was repeating more and more due to `v_texCoord + time`, it could run out of memory (despite the fact I don't really know how the texture is repeated in webgl).
So I tried to add a sinusoidal function to restrain the displacement but still the same slow down.
```
vec2 displacement = texture2D(u_displacementTexture, 0.4 * v_texCoord + sin(time)).rg * 2.0 - 1.0;
```

I have a feeling that the problem comes from the u_time uniform. I tried on js side to add `.toFixed(2)` but didn't help either.
I really need u_time to displace my displacementTexture to add the distorsion effect (on mobile I saw it is really not advised to use procedural noise : perlin or others as it may be slower than using a noise texture).

Temporary solution
---------

As I said, switching from mediump to highp precision solved the problem both on ipad and iphone, but as you say there is no perfect solution as it may not work on older phones.

Maybe you have an idea on what I could do to make my fragment shader mediump compatible? that would be great.

Anyway thanks for the detailed post and for all the tutos that helped me get started with webgl :)

**Comment by greggman** [comment]
Yes, it's a precision issue most likely. To fix it one way would be it limit time to values 0 to 1. So for example

    gl.uniform1f(timeUniform, time % 1);

In your shader this would work for your original code. For the sin code you'd have to change it to

     #define PI radians(180.0)
         ... sin(time * PI * 2)

repeating takes no memory. You could *almost* fake repeating like this

       texture2D(someTexture,  fract(someTexCoord));

or this

       texture2D(someTexture,  mod(someTexCoord, 1.0));

In fact if the filtering mode is NEAREST then the code above will work for repeating even of non-power-of-2 textures. Hopefully that lets you see how repeating takes no memory, it's just math.

The difference between the and actual reapeating is that if the sample mode is not NEAREST then the GPU has to read other pixels. For example if you're reading near the right most pixel the GPU might need to also read the left most pixel to do the filtering. It computes what pixel it needs using math similar to the math above but that math is internal to the GPU.
